services:
  - type: web
    name: laravel-whatsapp-bot
    plan: free
    region: ohio
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        value: base64:mQSKb+YiAkdebidqZMk6u3yyaqIo4N1b4lfbUv7Of0s=

databases:
  - name: mysql-db
    plan: free
    databaseName: ChatBot
    user: root